@startuml

title __ENTITIES's Class Diagram__\n

  namespace de.gematik.ti.cardreader.provider.pcsc.entities {
    class de.gematik.ti.cardreader.provider.pcsc.entities.CardReader {
        {static} - LOG : Logger
        - cardTerminal : CardTerminal
        + CardReader()
        + connect()
        + connect()
        + getCardTerminal()
        + getName()
        + initialize()
        + isCardPresent()
        + isInitialized()
        + toString()
        + waitForCardAbsent()
        + waitForCardPresent()
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.pcsc.entities {
    class de.gematik.ti.cardreader.provider.pcsc.entities.PcscCard {
        {static} - LOG : Logger
        - javaxCard : Card
        + PcscCard()
        + disconnect()
        + getATR()
        + getProtocol()
        + openBasicChannel()
        + openLogicalChannel()
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.pcsc.entities {
    class de.gematik.ti.cardreader.provider.pcsc.entities.PcscCardChannel {
        {static} - CARDREADER_BUFFER : String
        {static} - CARD_MAXAPDUBUFFERSIZE : String
        {static} - CARD_MAXRESPAPDUBUFFERSIZE : String
        {static} - LOG : Logger
        {static} - MINIMAL_ALLOCATE : int
        - allocateLength : int
        {static} - bufferSizeConfig : Map<String, Integer>
        - javaxCardChannel : CardChannel
        + PcscCardChannel()
        + close()
        + getCard()
        + getChannelNumber()
        + getMaxMessageLength()
        + getMaxResponseLength()
        + isExtendedLengthSupported()
        + setAllocateLength()
        + transmit()
    }
  }
  

  namespace de.gematik.ti.cardreader.provider.pcsc.entities {
    class de.gematik.ti.cardreader.provider.pcsc.entities.PcscCrpRuntimeException {
        {static} - serialVersionUID : long
        + PcscCrpRuntimeException()
    }
  }
  

  de.gematik.ti.cardreader.provider.pcsc.entities.CardReader .up.|> de.gematik.ti.cardreader.provider.api.ICardReader
  de.gematik.ti.cardreader.provider.pcsc.entities.PcscCard .up.|> de.gematik.ti.cardreader.provider.api.card.ICard
  de.gematik.ti.cardreader.provider.pcsc.entities.PcscCardChannel .up.|> de.gematik.ti.cardreader.provider.api.card.ICardChannel
  de.gematik.ti.cardreader.provider.pcsc.entities.PcscCardChannel o-- de.gematik.ti.cardreader.provider.pcsc.entities.PcscCard : pcscCard


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
